name: Build and Push Images to Harbor

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: harbor-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set created metadata
        id: meta
        shell: bash
        run: echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

      - name: Derive tags and (conditionally) sanitized creds
        id: vars
        shell: bash
        run: |
          set -euo pipefail

          REF="${GITHUB_REF}"
          SHA_TAG="sha-${GITHUB_SHA::7}"
          PUSH="false"
          BRANCH_SAFE=""

          if [[ "$REF" == refs/heads/main ]]; then
            PUSH="true"
          elif [[ "$REF" == refs/tags/* ]]; then
            PUSH="true"
          else
            BRANCH_SAFE=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | tr '/_' '--')
            PUSH="false"
          fi

          if [[ "$PUSH" == "true" ]]; then
            REGISTRY_RAW='${{ secrets.HARBOR_REGISTRY }}'
            REGISTRY="${REGISTRY_RAW#http://}"
            REGISTRY="${REGISTRY#https://}"
            REGISTRY="${REGISTRY%/}"

            USERNAME_RAW='${{ secrets.HARBOR_USERNAME }}'
            USERNAME_CLEAN=$(printf '%s' "${USERNAME_RAW}" | tr -d '\r\n')

            PASSWORD_RAW='${{ secrets.HARBOR_PASSWORD }}'
            PASSWORD_CLEAN=$(printf '%s' "${PASSWORD_RAW}" | tr -d '\r\n')

            PROJECT='${{ secrets.HARBOR_PROJECT }}'
            IMAGE_API="${REGISTRY}/${PROJECT}/gin-api"
            IMAGE_FE="${REGISTRY}/${PROJECT}/frontend"
          else
            REGISTRY=""
            USERNAME_CLEAN=""
            PASSWORD_CLEAN=""
            IMAGE_API="local/gin-api"
            IMAGE_FE="local/frontend"
          fi

          TAGS_API=""
          TAGS_FE=""

          if [[ "$REF" == refs/heads/main ]]; then
            TAGS_API+="${IMAGE_API}:latest\n${IMAGE_API}:${SHA_TAG}"
            TAGS_FE+="${IMAGE_FE}:latest\n${IMAGE_FE}:${SHA_TAG}"
          elif [[ "$REF" == refs/tags/* ]]; then
            VERSION_TAG="${REF#refs/tags/}"
            TAGS_API+="${IMAGE_API}:${VERSION_TAG}"
            TAGS_FE+="${IMAGE_FE}:${VERSION_TAG}"
          else
            TAGS_API+="${IMAGE_API}:${BRANCH_SAFE}-${SHA_TAG}"
            TAGS_FE+="${IMAGE_FE}:${BRANCH_SAFE}-${SHA_TAG}"
          fi

          {
            echo "push=${PUSH}"
            echo "registry=${REGISTRY}"
            echo "username=${USERNAME_CLEAN}"
            echo "password=${PASSWORD_CLEAN}"
            echo "api_tags<<EOF"
            printf '%b\n' "${TAGS_API}"
            echo "EOF"
            echo "fe_tags<<EOF"
            printf '%b\n' "${TAGS_FE}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Probe Harbor /v2 (401 is expected)
        if: steps.vars.outputs.push == 'true'
        run: |
          set -euo pipefail
          echo "Registry: ${{ steps.vars.outputs.registry }}"
          curl -sI "https://${{ steps.vars.outputs.registry }}/v2/" | sed -n '1p;/Www-Authenticate/p'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        if: steps.vars.outputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.vars.outputs.registry }}
          username: ${{ steps.vars.outputs.username }}
          password: ${{ steps.vars.outputs.password }}

      - name: Build gin-api image
        uses: docker/build-push-action@v6
        with:
          context: ./gin-api
          file: ./gin-api/Dockerfile
          push: ${{ steps.vars.outputs.push == 'true' }}
          tags: ${{ steps.vars.outputs.api_tags }}
          cache-from: type=gha,scope=gin-api
          cache-to: type=gha,mode=max,scope=gin-api
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ steps.vars.outputs.push == 'true' }}
          tags: ${{ steps.vars.outputs.fe_tags }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}

      - name: Debug login via docker CLI if previous login failed
        if: failure() && steps.vars.outputs.push == 'true'
        env:
          HARBOR_PASSWORD_CLEAN: ${{ steps.vars.outputs.password }}
          HARBOR_USERNAME_CLEAN: ${{ steps.vars.outputs.username }}
          HARBOR_REGISTRY_CLEAN: ${{ steps.vars.outputs.registry }}
        run: |
          set -euo pipefail
          printf '%s' "$HARBOR_PASSWORD_CLEAN" | docker login -u "$HARBOR_USERNAME_CLEAN" --password-stdin "$HARBOR_REGISTRY_CLEAN" || true
